# Generated by Django 4.2.7 on 2023-11-02 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studen_number',
            new_name='student_number',
        ),
    ]
